export interface WalkthroughStep {
  id: string
  title: string
  description: string
  elementSelector: string // CSS selector or data attribute
  position?: 'top' | 'bottom' | 'left' | 'right' | 'center'
  align?: 'start' | 'center' | 'end'
  offset?: { x: number; y: number }
  highlight?: boolean // Whether to highlight the element
  scrollIntoView?: boolean
  delay?: number // Delay before showing this step (ms)
  icon?: string // Emoji or icon identifier
}

export const walkthroughConfig: Record<string, WalkthroughStep[]> = {
  '/': [
    {
      id: 'nav',
      title: '🚀 Navigation Bar',
      description: 'Use this area to explore different modules and features. All your main tools are accessible from here.',
      elementSelector: 'nav',
      position: 'bottom',
      align: 'center',
      highlight: true,
      scrollIntoView: false,
      icon: '🚀',
    },
    {
      id: 'data-catalog',
      title: '📚 Data Catalog',
      description: 'Access verified data on 658,859+ healthcare providers across the US. Browse by category, filter by location, and export custom datasets.',
      elementSelector: '[href="/data-catalog"]',
      position: 'bottom',
      align: 'start',
      highlight: true,
      scrollIntoView: true,
      icon: '📚',
    },
    {
      id: 'insights',
      title: '📰 Healthcare Insights',
      description: 'Real-time healthcare news, market intelligence, and industry trends powered by AI. Get sales-focused recommendations and identify opportunities.',
      elementSelector: '[href="/insights"]',
      position: 'bottom',
      align: 'start',
      highlight: true,
      scrollIntoView: true,
      icon: '📰',
    },
    {
      id: 'bookmarks',
      title: '🔖 Bookmarks',
      description: 'Save and monitor your favorite healthcare facilities. View news timelines, search within bookmarks, and track competitor activity.',
      elementSelector: '[href="/bookmarks"]',
      position: 'bottom',
      align: 'start',
      highlight: true,
      scrollIntoView: true,
      icon: '🔖',
    },
    {
      id: 'search',
      title: '🔍 Smart Search',
      description: 'Use natural language to find facilities. Try "urgent care centers in Texas" or "hospitals with over 500 beds". Our AI understands context and intent.',
      elementSelector: '[href="/search"]',
      position: 'bottom',
      align: 'start',
      highlight: true,
      scrollIntoView: true,
      icon: '🔍',
    },
    {
      id: 'ai-assistant',
      title: '💬 AI Assistant',
      description: 'Need help? Click here anytime to chat with our AI assistant. Ask questions, get feature guidance, or navigate the platform. Available 24/7!',
      elementSelector: '.fixed.bottom-8.right-8, [data-ai-assistant]',
      position: 'left',
      align: 'center',
      highlight: true,
      scrollIntoView: true,
      icon: '💬',
    },
    {
      id: 'complete',
      title: '🎉 You\'re All Set!',
      description: 'You now know the essentials of HealthData AI. Start exploring any feature—each one is designed to help you make data-driven decisions. You can replay this tour anytime from the Help button!',
      elementSelector: '',
      position: 'center',
      align: 'center',
      highlight: false,
      scrollIntoView: false,
      icon: '🎉',
    },
  ],
  '/dashboard': [
    {
      id: 'nav',
      title: '🚀 Navigation',
      description: 'Use this area to navigate between different sections of the platform.',
      elementSelector: 'nav',
      position: 'bottom',
      align: 'center',
      highlight: true,
      icon: '🚀',
    },
    {
      id: 'metrics',
      title: '📊 Key Metrics',
      description: 'These cards show your overall performance indicators. Hover to see detailed breakdowns and trends.',
      elementSelector: '[data-tour="metrics"], .grid.grid-cols-4',
      position: 'bottom',
      align: 'center',
      highlight: true,
      scrollIntoView: true,
      icon: '📊',
    },
    {
      id: 'activity',
      title: '📈 Recent Activity',
      description: 'Monitor your recent actions, calls, and interactions. Stay updated with real-time activity feeds.',
      elementSelector: '[data-tour="activity"]',
      position: 'right',
      align: 'start',
      highlight: true,
      scrollIntoView: true,
      icon: '📈',
    },
  ],
  '/data-catalog': [
    {
      id: 'header',
      title: '📚 Data Catalog Overview',
      description: 'Welcome to the heart of HealthData AI! Here you\'ll find 658,859+ verified healthcare providers organized by category.',
      elementSelector: '.container, .max-w-7xl',
      position: 'top',
      align: 'center',
      highlight: false,
      icon: '📚',
    },
    {
      id: 'search',
      title: '🔍 Quick Search',
      description: 'Type here to instantly find specific facility categories. Try "hospital", "pharmacy", or "clinic". The search is fast and intelligent!',
      elementSelector: 'input[type="text"]',
      position: 'bottom',
      align: 'start',
      highlight: true,
      scrollIntoView: true,
      icon: '🔍',
    },
    {
      id: 'custom-dataset',
      title: '🎯 Custom Dataset Builder',
      description: 'Create filtered datasets by state, city, facility type, and more. Perfect for targeted campaigns, market analysis, and competitive intelligence.',
      elementSelector: '.bg-gradient-to-br',
      position: 'top',
      align: 'center',
      highlight: true,
      scrollIntoView: true,
      icon: '🎯',
    },
    {
      id: 'categories',
      title: '📋 Browse Categories',
      description: 'Each card shows a category with live provider counts. Click any card to drill down into specific facility types and explore detailed information.',
      elementSelector: '.grid.grid-cols-3, .grid.grid-cols-2',
      position: 'top',
      align: 'center',
      highlight: true,
      scrollIntoView: true,
      icon: '📋',
    },
  ],
  '/insights': [
    {
      id: 'header',
      title: '📰 Healthcare Insights Hub',
      description: 'Real-time news and market intelligence powered by advanced AI. Stay ahead of industry trends, identify sales opportunities, and make informed decisions.',
      elementSelector: '.container, .max-w-7xl',
      position: 'top',
      align: 'center',
      highlight: false,
      icon: '📰',
    },
    {
      id: 'tabs',
      title: '🏷️ Filter by Category',
      description: 'Browse insights by type: Expansion, Technology, M&A, Policy, Funding, and more. Focus on what matters most to your business goals.',
      elementSelector: '[role="tablist"]',
      position: 'bottom',
      align: 'center',
      highlight: true,
      scrollIntoView: true,
      icon: '🏷️',
    },
    {
      id: 'articles',
      title: '💡 Pro Tip',
      description: 'Use the Refresh button to get the latest news. Click "Read More" on any article for detailed AI-powered analysis with actionable sales recommendations.',
      elementSelector: '[data-tour="articles"]',
      position: 'top',
      align: 'center',
      highlight: false,
      icon: '💡',
    },
  ],
  '/bookmarks': [
    {
      id: 'header',
      title: '🔖 Your Bookmarks',
      description: 'Track competitor facilities, monitor prospects, and stay updated on organizations in your territory. Your personal intelligence dashboard!',
      elementSelector: '.container, .max-w-7xl',
      position: 'top',
      align: 'center',
      highlight: false,
      icon: '🔖',
    },
    {
      id: 'search',
      title: '🔍 Search Bookmarks',
      description: 'Quickly find specific facilities in your saved bookmarks by name, location, or category. You can also search news specifically for bookmarked facilities.',
      elementSelector: 'input[type="text"]',
      position: 'bottom',
      align: 'start',
      highlight: true,
      scrollIntoView: true,
      icon: '🔍',
    },
  ],
  '/search': [
    {
      id: 'header',
      title: '🔍 Smart Search',
      description: 'Our AI-powered search understands natural language. No need for complex filters—just ask what you\'re looking for in plain English.',
      elementSelector: '.container, .max-w-4xl',
      position: 'top',
      align: 'center',
      highlight: false,
      icon: '🔍',
    },
    {
      id: 'input',
      title: '💬 Natural Language Queries',
      description: 'Try queries like "urgent care centers in California" or "hospitals with over 500 beds in New York". The AI understands context and finds perfect matches.',
      elementSelector: 'input[type="text"], textarea',
      position: 'bottom',
      align: 'center',
      highlight: true,
      scrollIntoView: true,
      icon: '💬',
    },
  ],
}

// Default steps for pages not in config
export const defaultWalkthroughSteps: WalkthroughStep[] = [
  {
    id: 'welcome',
    title: '🎯 HealthData AI Tour',
    description: 'Navigate to the home page, data catalog, insights, bookmarks, or search to explore specific features with guided tours. Each page has its own interactive walkthrough!',
    elementSelector: '',
    position: 'center',
    align: 'center',
    highlight: false,
    icon: '🎯',
  },
]

